- name: backend
  hosts: backend
  become: yes
  vars:
    mysql: mysql.devopspractice.help
    mysql_root_password: ExpenseApp@1
  tasks:
    - name: install pip
      ansible.builtin.pip:
        name:
          - PyMySQL
        executable: pip3.9

    - name: Disable default nodejs
      ansible.builtin.package:
        name: nodejs
        state: removed
    
    - name: Enable nodejs 20
      ansible.builtin.package:
        name: nodejs
        state: present
        enablerepo: nodejs:20

    # - name: disable nodejs
    #   ansible.builtin.command: "dnf module disable nodejs -y"

    # - name: enable nodejs
    #   ansible.builtin.command: "dnf module enable nodejs:20 -y"
    
    - name: install nodejs and mysql
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - mysql
    
    - name: user add
      ansible.builtin.user:
        name: expense

    - name: Create a directory
      ansible.builtin.file:
        path: /app
        state: directory
      
    - name: download package
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip

    - name: unzip backend code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes

    - name: npm package install
      community.general.npm:
        path: /app

    - name: copy file
      ansible.builtin.copy:
        src: /home/ec2-user/expense-ansible/backend.service
        dest: /etc/systemd/system/backend.service

    - name: Connect to mysql server
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: mysql.devopspractice.help
      register: mysql_info
      ignore_errors: true
    
    - name: print output
      ansible.builtin.debug:
        msg: "{{ mysql_info }}"

    - name: set root login_password
      ansible.builtin.command: "mysql -h '{{ mysql }}' -uroot -p'{{ mysql_root_password }}' < /app/schema/backend.sql"
      when: mysql_info.failed is false

    - name: backend daemon reload
      ansible.builtin.systemd:
          name: backend
          daemon_reload: true
          state: restarted
          enabled: true
